version: "3.9"

services:
  mysql:
    image: mysql:latest
    container_name: notetask-mysql
    volumes:
      - mysql_data:/var/lib/mysql   
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}

  server:
    build: ./server
    container_name: notetask-server
    ports:
      - "3001:3000"
    depends_on:
      - mysql
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      MYSQL_ROOT_PASSWORD: yoshani#28
      MYSQL_DATABASE: notetask
      MYSQL_USER: root

  client:
    build: ./client
    container_name: notetask-client
    ports:
      - "5173:5173"
    depends_on:
      - server
    stdin_open: true
    tty: true
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  mysql_data:
